""" __init__ for groups """
from groups.m3dmagic_group import M3DMAGIC  # noqa: F401
from groups.mdata_group import MDATA  # noqa: F401
from groups.named_object_group import NAMEDOBJECT  # noqa: F401
from groups.n_tri_object_group import NTRIOBJECT  # noqa: F401
from groups.point_array_group import POINTARRAY  # noqa: F401
from groups.face_array_group import FACEARRAY  # noqa: F401
from groups.tex_verts_group import TEXVERTS  # noqa: F401
from groups.mesh_matrix_group import MESHMATRIX  # noqa: F401
from groups.msh_mat_group_group import MSHMATGROUP  # noqa: F401
from groups.smooth_group_group import SMOOTHGROUP  # noqa: F401
from groups.kfdata_group import KFDATA  # noqa: F401
from groups.object_node_tag_group import OBJECTNODETAG  # noqa: F401
from groups.node_hdr_group import NODEHDR  # noqa: F401
from groups.m3d_version_group import M3DVERSION  # noqa: F401
from groups.mesh_version_group import MESHVERSION  # noqa: F401
from groups.mat_entry_group import MATENTRY  # noqa: F401
from groups.master_scale_group import MASTERSCALE  # noqa: F401
from groups.point_flag_array_group import POINTFLAGARRAY  # noqa: F401
from groups.mesh_color_group import MESHCOLOR  # noqa: F401
