""" __init__ for groups """
from groups.m3dmagic_group import M3DMAGIC  # noqa: F401
from groups.mdata_group import MDATA  # noqa: F401
from groups.named_object_group import NAMEDOBJECT  # noqa: F401
from groups.n_tri_object_group import NTRIOBJECT  # noqa: F401
from groups.point_array_group import POINTARRAY  # noqa: F401
from groups.face_array_group import FACEARRAY  # noqa: F401
from groups.tex_verts_group import TEXVERTS  # noqa: F401
from groups.mesh_matrix_group import MESHMATRIX  # noqa: F401
from groups.msh_mat_group_group import MSHMATGROUP  # noqa: F401
from groups.smooth_group_group import SMOOTHGROUP  # noqa: F401
from groups.kfdata_group import KFDATA  # noqa: F401
from groups.object_node_tag_group import OBJECTNODETAG  # noqa: F401
from groups.node_hdr_group import NODEHDR  # noqa: F401
from groups.m3d_version_group import M3DVERSION  # noqa: F401
from groups.mesh_version_group import MESHVERSION  # noqa: F401
from groups.mat_entry_group import MATENTRY  # noqa: F401
from groups.master_scale_group import MASTERSCALE  # noqa: F401
from groups.point_flag_array_group import POINTFLAGARRAY  # noqa: F401
from groups.mesh_color_group import MESHCOLOR  # noqa: F401
from groups.mat_name_group import MATNAME  # noqa: F401
from groups.mat_ambient_group import MATAMBIENT  # noqa: F401
from groups.mat_diffuse_group import MATDIFFUSE  # noqa: F401
from groups.mat_specular_group import MATSPECULAR  # noqa: F401
from groups.mat_shininess_group import MATSHININESS  # noqa: F401
from groups.mat_shin_2pct_group import MATSHIN2PCT  # noqa: F401
from groups.mat_shin_3pct_group import MATSHIN3PCT  # noqa: F401
from groups.mat_transparency_group import MATTRANSPARENCY  # noqa: F401
from groups.mat_xpfall_group import MATXPFALL  # noqa: F401
from groups.mat_refblur_group import MATREFBLUR  # noqa: F401
from groups.mat_selfillum_group import MATSELFILLUM  # noqa: F401
from groups.mat_two_side_group import MATTWOSIDE  # noqa: F401
from groups.mat_decal_group import MATDECAL  # noqa: F401
from groups.mat_additive_group import MATADDITIVE  # noqa: F401
from groups.mat_selfil_pct_group import MATSELFILPCT  # noqa: F401
from groups.mat_wire_group import MATWIRE  # noqa: F401
from groups.mat_super_smp_group import MATSUPERSMP  # noqa: F401
from groups.mat_wire_size_group import MATWIRESIZE  # noqa: F401
from groups.mat_face_map_group import MATFACEMAP  # noqa: F401
from groups.mat_xpfallin_group import MATXPFALLIN  # noqa: F401
from groups.mat_phong_soft_group import MATPHONGSOFT  # noqa: F401
from groups.mat_wire_abs_group import MATWIREABS  # noqa: F401
from groups.mat_shading_group import MATSHADING  # noqa: F401
from groups.mat_tex_map_group import MATTEXMAP  # noqa: F401
from groups.color_f_group import COLORF  # noqa: F401
from groups.color_24_group import COLOR24  # noqa: F401
from groups.lin_color_24_group import LINCOLOR24  # noqa: F401
from groups.lin_color_f_group import LINCOLORF  # noqa: F401
from groups.int_percentage_group import INTPERCENTAGE  # noqa: F401
from groups.float_percentage_group import FLOATPERCENTAGE  # noqa: F401
